# Etapa 1: Usar uma imagem base do Python
FROM python:3.10-slim

# Etapa 2: Configurar o diretório de trabalho
WORKDIR /app

# Etapa 3: Copiar os arquivos do projeto para o container
COPY . .

# Etapa 4: Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Etapa 5: Executar script de inicialização
RUN python init_db.py

# Etapa 6: Expor a porta usada pela aplicação
EXPOSE 8000

# Etapa 7: Comando para rodar a aplicação
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
